image: node:12

stages:
  - deploy

.deploy:
  stage: deploy
  tags:
    - nodejs-outwall
  cache:
    key: cache
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist_electron
    expire_in: 1 day

    
deploy-master:
  extends: .deploy
  script:
    - yarn
    - yarn run build
    - yarn run build-background
    - yarn run pack-vue
    - node print_version.js
    - mv ./dist_electron/dist_vue.asar ./dist_electron/app_$CI_COMMIT_SHA.asar
    - node upload.js
  environment:
    name: master
  only:
    - master

deploy-dev:
  extends: .deploy
  script:
    - yarn
    - yarn run build-dev
    - yarn run build-background-dev
    - yarn run pack-vue
    - node print_version.js
    - mv ./dist_electron/dist_vue.asar ./dist_electron/app_$CI_COMMIT_SHA.asar
    - node upload.js
  environment:
    name: staging/dev
  only:
    - dev

deploy-release:
  extends: .deploy
  script:
    - yarn install --ignore-optional
    - yarn run build-release
    - yarn run build-background-release
    - yarn run pack-vue
    - node print_version.js
    - mv ./dist_electron/dist_vue.asar ./dist_electron/app_$CI_COMMIT_SHA.asar
    - node upload.js
  environment:
    name: staging/release
  only:
    - /^release-([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$/
