stages:
  - install
  - build
  - deploy

variables:
  ELECTRON_MIRROR: "https://npm.taobao.org/mirrors/electron/"
  PHANTOMJS_CDNURL: "https://npm.taobao.org/dist/phantomjs"

# 下载依赖
install:
  stage: install
  image: node:12
  tags:
    - nodejs
  cache:
    key: cache
    paths:
      - node_modules/
  script:
    - yarn
  only:
    - master
    - dev
    - /^release-([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$/

# 打包
.build:
  stage: build
  image: node:12
  tags:
    - nodejs
  cache:
    key: cache
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist_electron/
    expire_in: 1 day

build-master:
  extends: .build
  script:
    - yarn build-asar
    - node print_version.js production
    - mv ./dist_electron/dist_vue.asar ./dist_electron/app_$CI_COMMIT_SHA.asar
  environment:
    name: master
  only:
    - master

build-dev:
  extends: .build
  script:
    - yarn build-asar-dev
    - node print_version.js development
    - mv ./dist_electron/dist_vue.asar ./dist_electron/app_$CI_COMMIT_SHA.asar
  environment:
    name: staging/dev
  only:
    - dev

build-release:
  extends: .build
  script:
    - yarn build-asar-release
    - node print_version.js release
    - mv ./dist_electron/dist_vue.asar ./dist_electron/app_$CI_COMMIT_SHA.asar

  environment:
    name: staging/release
  only:
    - /^release-([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$/

# 上传又拍云
.deploy:
  stage: deploy
  image: registry-vpc.cn-hangzhou.aliyuncs.com/mainto_micro/environment-node:10-deploy
  script:
    - node /deploy-scripts/cloudUpload.js

deploy-master:
  extends: .deploy
  environment:
    name: master
  only:
    - master

deploy-dev:
  extends: .deploy
  environment:
    name: staging/dev
  only:
    - dev

deploy-release:
  extends: .deploy
  environment:
    name: staging/release
  only:
    - /^release-([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$/