image: node:12

stages:
  - deploy

.deploy:
  stage: deploy
  cache:
    key: cache
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist_electron
    expire_in: 1 day

    
deploy-master:
  extends: .deploy
  script:
    - yarn install
    - yarn run build
    - yarn run build-background
    - yarn run pack-vue
    - node print_version.js
    - mv ./dist_electron/dist_vue.asar ./dist_electron/app_$CI_COMMIT_SHA.asar
    - node upload.js
  environment:
    name: master
  only:
    - master

deploy-dev:
  extends: .deploy
  image: registry-vpc.cn-hangzhou.aliyuncs.com/mainto_micro/environment-node:10-deploy
  script:
    - yarn install
    - yarn run build-dev
    - yarn run build-background-dev
    - yarn run pack-vue
    - node print_version.js
    - mv ./dist_electron/dist_vue.asar ./dist_electron/app_$CI_COMMIT_SHA.asar
    - node upload.js
    - PROJECT_DIR=`pwd`
    - SOURCE_FOLDER='dist_vue'
    - cd /deploy-scripts && node deploySourceMap.js $PROJECT_DIR/$SOURCE_FOLDER
  environment:
    name: staging/dev
  only:
    - dev

deploy-release:
  extends: .deploy
  script:
    - yarn install
    - yarn run build-release
    - yarn run build-background-release
    - yarn run pack-vue
    - node print_version.js
    - mv ./dist_electron/dist_vue.asar ./dist_electron/app_$CI_COMMIT_SHA.asar
    - node upload.js
  environment:
    name: staging/release
  only:
    - /^release-([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$/
