stages:
  - install
  - build
  - deploy

# 下载依赖
install:
  stage: install
  image: node:12
  tags:
    - nodejs-outwall
  cache:
    key: cache
    paths:
      - node_modules/
  script:
    - yarn install

# 打包
.build:
  stage: build
  image: node:12
  tags:
    - nodejs-outwall
  cache:
    key: cache
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist_electron/
    expire_in: 1 day

build-master:
  extends: .build
  script:
    - yarn build
    - yarn run build-background
    - yarn run pack-vue
    - node print_version.js
    - mv ./dist_electron/dist_vue.asar ./dist_electron/app_$CI_COMMIT_SHA.asar
  environment:
    name: master
  only:
    - master

build-dev:
  extends: .build
  script:
    - yarn run build-dev
    - yarn run build-background-dev
    - yarn run pack-vue
    - node print_version.js
    - mv ./dist_electron/dist_vue.asar ./dist_electron/app_$CI_COMMIT_SHA.asar
  environment:
    name: staging/dev
  only:
    - dev

build-release:
  extends: .build
  script:
    - yarn run build-release
    - yarn run build-background-release
    - yarn run pack-vue
    - node print_version.js
    - mv ./dist_electron/dist_vue.asar ./dist_electron/app_$CI_COMMIT_SHA.asar
  environment:
    name: staging/release
  only:
    - /^release-([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$/

# 上传又拍云
.deploy:
  stage: deploy
  image: registry-vpc.cn-hangzhou.aliyuncs.com/mainto_micro/environment-node:10-deploy
    
deploy-master:
  extends: .deploy
  script:
    - node upload.js
  environment:
    name: master
  only:
    - master

deploy-dev:
  extends: .deploy
  script:
    - node upload.js
  environment:
    name: staging/dev
  only:
    - dev

deploy-release:
  extends: .deploy
  script:
    - node upload.js
  environment:
    name: staging/release
  only:
    - /^release-([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$/
