// doc: https://nhnent.github.io/tui.editor/api/latest/ToastUIEditor.html#ToastUIEditor
export default {
  minHeight: '500px',
  height: '100%',
  viewer: true,
  language: 'zh_CN',
  initialEditType: 'markdown',
  initialValue: '',
  previewStyle: 'vertical',
  useCommandShortcut: true,
  useDefaultHTMLSanitizer: true,
  usageStatistics: false,
  hideModeSwitch: false,
  theme: 'forest', // 'default', 'forest', 'dark', 'neutral'
  editorEvents: [
    'load',
    'change',
    'stateChange',
    'focus',
    'blur',
  ],
  toolbarItems: [
    'heading',
    'bold',
    'italic',
    'strike',
    'divider',
    'hr',
    'quote',
    'divider',
    'ul',
    'ol',
    'task',
    'indent',
    'outdent',
    'divider',
    'table',
    'image',
    'link',
    'divider',
    'code',
    'codeblock',
  ]
}
